# Change these first
owner: lndr0x
repo: status
user-agent: lndr0x

# Add your sites here
sites:
  - name: Placeholder Site (Will be replaced )
    url: https://example.com

# Status website
status-website:
  # Add your custom domain below, or remove the next line if you don't have a custom domain
  # cname: demo.upptime.js.org
  # Choose a name for your status site
  name: Status Page
  # Theme
  theme: light
  # Logo
  # logo-url: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  # Intro text
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This status page is powered by **Upptime** and is currently monitoring the placeholder site.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime schedule
workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 0 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  update: "*/5 * * * *"

# commit messages
commitMessages:
  commitAuthorName: "Upptime Bot"
  commitAuthorEmail: "73812580+upptime-bot@users.noreply.github.com"
